### ISSUE TITLE
Issue in scheduling next morning

### ISSUE THREAD

**Issue by henrydennis** [amitness/habitist#7]
Okay. First I though it was an issue with timezone. Then because I scheduled it in the morning. Now I am back to timezone. For some reason non of the habits are increasing...

I can see that they API key is working and it is looping through the to do items.

**Comment by amitness** [comment]
@henrydennis I hadn't faced this issue because I was testing only in my timezone. There is a solution, you can try. Calculate the time when it's 12:00 AM in UTC in your timezone. 

For example, I'm from Nepal where we're 5:45 hours ahead of UTC. So, when it's 12:00AM, we are at 5:45AM in Nepal. Now, I will set the time to trigger this API in IFTTT as 6:00AM so that the timezone calculation works. Do the same for your timezone.
